export const products = [
  {
    asin: "B0CWXNS552",
    product_title: "Apple AirTag",
    product_price: "$24.99",
    product_original_price: "$29.00",
    currency: "USD",
    product_star_rating: "4.6",
    product_num_ratings: 2027,
    product_url: "https://www.amazon.com/dp/B0CWXNS552",
    product_photo:
      "https://m.media-amazon.com/images/I/71rP7f78eFL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 11,
    product_minimum_offer_price: "$23.33",
    is_best_seller: false,
    is_amazon_choice: true,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "10K+ bought in past month",
    delivery: "FREE delivery Wed, Jul 10 on $35 of items shipped by Amazon",
    has_variations: false,
  },
  {
    asin: "B0D5FZGY8W",
    product_title:
      "URO Vaginal Probiotics for Women pH Balance with Prebiotics &amp; Lactobacillus Probiotic Blend - Women&#x27;s Vaginal Health Supplement - Promote Healthy Vaginal Odor &amp; Vaginal Flora, 60 Count (Pack of 1)",
    product_price: "$28.79",
    unit_price: "$0.48",
    unit_count: 60,
    product_original_price: "$31.99",
    currency: "USD",
    product_star_rating: "4.5",
    product_num_ratings: 376,
    product_url: "https://www.amazon.com/dp/B0D5FZGY8W",
    product_photo:
      "https://m.media-amazon.com/images/I/61tYAHJi3LL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$28.79",
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: true,
    sales_volume: "100K+ bought in past month",
    delivery: "FREE delivery Wed, Jul 10 on $35 of items shipped by Amazon",
    has_variations: false,
  },
  {
    asin: "1665955430",
    product_title: "Reckless (The Powerless Trilogy)",
    product_price: "$14.97",
    product_original_price: "$21.99",
    currency: "USD",
    product_star_rating: "4.5",
    product_num_ratings: 2160,
    product_url: "https://www.amazon.com/dp/1665955430",
    product_photo:
      "https://m.media-amazon.com/images/I/81q6ecxcZUL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 37,
    product_minimum_offer_price: "$14.96",
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "List: ",
    delivery: "FREE delivery Wed, Jul 10 on $35 of items shipped by Amazon",
    has_variations: false,
  },
  {
    asin: "B0CS12LZLS",
    product_title: "NESCAFÉ Gold Espresso Blonde, Instant Coffee, 3.5 oz",
    product_price: "$6.68",
    unit_price: "$1.91",
    unit_count: 3,
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.6",
    product_num_ratings: 278,
    product_url: "https://www.amazon.com/dp/B0CS12LZLS",
    product_photo:
      "https://m.media-amazon.com/images/I/71tPLfAANDL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$6.68",
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "10K+ bought in past month",
    delivery:
      "FREE delivery Jul 15 - 17 on $35 of items shipped by AmazonOr fastest delivery Jul 14 - 16",
    has_variations: false,
  },
  {
    asin: "B0CSBZVR6F",
    product_title:
      "2 Pack Continuous Spray Bottles - Ultra Fine Mist Sprayer | Water Spray Bottle For Hair Mister Spray Bottle | Hair Spray Bottles For Hairstyling, Cleaning, Salons - 2pk 6.8 OZ / 200 ML",
    product_price: "$8.48",
    product_original_price: "$8.99",
    currency: "USD",
    product_star_rating: "4.3",
    product_num_ratings: 2110,
    product_url: "https://www.amazon.com/dp/B0CSBZVR6F",
    product_photo:
      "https://m.media-amazon.com/images/I/71Grc+h-AtL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 5,
    product_minimum_offer_price: "$2.45",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: true,
    sales_volume: "20K+ bought in past month",
    delivery: "FREE delivery Wed, Jul 10 on $35 of items shipped by Amazon",
    has_variations: false,
  },
  {
    asin: "1668032147",
    product_title: "Protocols: An Operating Manual for the Human Body",
    product_price: "$21.39",
    product_original_price: "$35.00",
    currency: "USD",
    product_star_rating: null,
    product_num_ratings: 0,
    product_url: "https://www.amazon.com/dp/1668032147",
    product_photo:
      "https://m.media-amazon.com/images/I/61tDi3+vgzL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$21.39",
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "List: ",
    delivery:
      "FREE delivery Mon, Apr 28, 2025 on $35 of items shipped by AmazonOr fastest delivery Tue, Apr 22, 2025 This title will be released on April 22, 2025.",
    has_variations: false,
  },
  {
    asin: "0593657470",
    product_title: "On Call: A Doctor&#x27;s Journey in Public Service",
    product_price: "$22.59",
    product_original_price: "$36.00",
    currency: "USD",
    product_star_rating: "4.7",
    product_num_ratings: 780,
    product_url: "https://www.amazon.com/dp/0593657470",
    product_photo:
      "https://m.media-amazon.com/images/I/813MUJ9ftIL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$22.59",
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "List: ",
    delivery: "FREE delivery Wed, Jul 10 on $35 of items shipped by Amazon",
    has_variations: false,
  },
  {
    asin: "B0CV4FQPY1",
    product_title:
      "Bounty Select-A-Size Paper Towels, White, 8 Triple Rolls = 24 Regular Rolls",
    product_price: "$22.18",
    unit_price: "$2.05",
    unit_count: 11,
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.8",
    product_num_ratings: 35935,
    product_url: "https://www.amazon.com/dp/B0CV4FQPY1",
    product_photo:
      "https://m.media-amazon.com/images/I/81jYzN4cAdL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 15,
    product_minimum_offer_price: "$21.00",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "40K+ bought in past month",
    delivery: "FREE delivery Wed, Jul 10 on $35 of items shipped by Amazon",
    has_variations: false,
  },
  {
    asin: "B0C9N2L56X",
    product_title:
      "The Anxious Generation: How the Great Rewiring of Childhood Is Causing an Epidemic of Mental Illness",
    product_price: "$0.00",
    product_original_price: "$20.25",
    currency: "USD",
    product_star_rating: "4.7",
    product_num_ratings: 1764,
    product_url: "https://www.amazon.com/dp/B0C9N2L56X",
    product_photo:
      "https://m.media-amazon.com/images/I/81N4drWaxuL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$0.00",
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "Other formats: ",
    delivery: "Available instantly",
    has_variations: false,
  },
  {
    asin: "1464221138",
    product_title: "The Housemaid Is Watching",
    product_price: "$12.71",
    product_original_price: "$17.99",
    currency: "USD",
    product_star_rating: "4.2",
    product_num_ratings: 56803,
    product_url: "https://www.amazon.com/dp/1464221138",
    product_photo:
      "https://m.media-amazon.com/images/I/91OSM58Y-pL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 52,
    product_minimum_offer_price: "$10.50",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "List: ",
    delivery: "FREE delivery Wed, Jul 10 on $35 of items shipped by Amazon",
    has_variations: false,
  },
  {
    asin: "B0CSYG2CP3",
    product_title:
      "Car Carplay Cable for iPhone 15 15 Pro Max 15 Plus Cable, USB A to USB C for Carplay USB C Cord, iPad usb C Cable 10th Gen iPad Pro iPad Air 5th 4th Mini 6th Gen Car Charger Cable Cord Replacement 3FT",
    product_price: "$8.19",
    product_original_price: "$8.99",
    currency: "USD",
    product_star_rating: "4.6",
    product_num_ratings: 596,
    product_url: "https://www.amazon.com/dp/B0CSYG2CP3",
    product_photo:
      "https://m.media-amazon.com/images/I/61fpyOCUDML._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$8.19",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "10K+ bought in past month",
    delivery: "FREE delivery Wed, Jul 10 on $35 of items shipped by Amazon",
    has_variations: false,
  },
  {
    asin: "B07RFSSYBH",
    product_title:
      "Atomic Habits: An Easy &amp; Proven Way to Build Good Habits &amp; Break Bad Ones",
    product_price: "$0.00",
    product_original_price: "$18.00",
    currency: "USD",
    product_star_rating: "4.8",
    product_num_ratings: 129547,
    product_url: "https://www.amazon.com/dp/B07RFSSYBH",
    product_photo:
      "https://m.media-amazon.com/images/I/71F4+7rk2eL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$0.00",
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "Other formats: ",
    delivery: "Available instantly",
    has_variations: false,
  },
  {
    asin: "B0CQDFPMQW",
    product_title:
      "LMNT Zero-Sugar Electrolytes - Variety Pack Bundle - Drink Mix | No Dodgy Ingredients | Keto &amp; Paleo Friendly | 36 Sticks",
    product_price: "$59.99",
    unit_price: "$7.90",
    unit_count: 8,
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.5",
    product_num_ratings: 17598,
    product_url: "https://www.amazon.com/dp/B0CQDFPMQW",
    product_photo:
      "https://m.media-amazon.com/images/I/81qGH-6amTL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$59.99",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "20K+ bought in past month",
    delivery: "FREE delivery Wed, Jul 10",
    has_variations: false,
  },
  {
    asin: "B0CP93N5S2",
    product_title: "All the Colors of the Dark",
    product_price: "$13.99",
    product_original_price: "$30.00",
    currency: "USD",
    product_star_rating: "4.7",
    product_num_ratings: 856,
    product_url: "https://www.amazon.com/dp/B0CP93N5S2",
    product_photo:
      "https://m.media-amazon.com/images/I/81RBcyIyl2L._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$13.99",
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "Print List Price: ",
    delivery: "Available instantly",
    has_variations: false,
  },
  {
    asin: "B0D3PBB78P",
    product_title: "EA SPORTS College Football 25 - PlayStation 5",
    product_price: "$69.99",
    product_original_price: null,
    currency: "USD",
    product_star_rating: null,
    product_num_ratings: 0,
    product_url: "https://www.amazon.com/dp/B0D3PBB78P",
    product_photo:
      "https://m.media-amazon.com/images/I/81aE0GBL2mL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$69.99",
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "Jul 19, 2024",
    delivery: "FREE deliveryThis item will be released on July 19, 2024.",
    has_variations: false,
  },
  {
    asin: "B0D49X2P79",
    product_title: "Twister [4K UHD]",
    product_price: "$24.96",
    product_original_price: "$33.99",
    currency: "USD",
    product_star_rating: "4.7",
    product_num_ratings: 2119,
    product_url: "https://www.amazon.com/dp/B0D49X2P79",
    product_photo:
      "https://m.media-amazon.com/images/I/71HH+CAgaJL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$24.96",
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "2K+ bought in past month",
    delivery:
      "FREE delivery Wed, Jul 17 on $35 of items shipped by AmazonOr fastest delivery Tue, Jul 16 This title will be released on July 9, 2024.",
    has_variations: false,
  },
  {
    asin: "B0CLKQF5HR",
    product_title: "Swan Song",
    product_price: "$14.99",
    product_original_price: "$30.00",
    currency: "USD",
    product_star_rating: "4.5",
    product_num_ratings: 7102,
    product_url: "https://www.amazon.com/dp/B0CLKQF5HR",
    product_photo:
      "https://m.media-amazon.com/images/I/71dSn3QCY6L._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$14.99",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "Print List Price: ",
    delivery: "Available instantly",
    has_variations: false,
  },
  {
    asin: "B0D2PKQGQV",
    product_title:
      "Hanes Men&#x27;s Pocket Undershirt Pack, Cotton Crew Neck T-Shirt, Moisture Wicking Tee, Assorted 6-Pack",
    product_price: "$21.98",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.4",
    product_num_ratings: 24675,
    product_url: "https://www.amazon.com/dp/B0D2PKQGQV",
    product_photo:
      "https://m.media-amazon.com/images/I/81v4ewQrCgL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$21.98",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "500+ bought in past month",
    delivery: "FREE delivery Wed, Jul 10 on $35 of items shipped by Amazon",
    has_variations: true,
  },
  {
    asin: "B0D1P158BH",
    product_title: "UEFA EURO 2024 Official",
    product_price: "$0.00",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "3.4",
    product_num_ratings: 56,
    product_url: "https://www.amazon.com/dp/B0D1P158BH",
    product_photo:
      "https://m.media-amazon.com/images/I/71Eq+TtkQRL._AC_UL960_FMwebp_QL65_.png",
    product_num_offers: 1,
    product_minimum_offer_price: "$0.00",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "Jun 14, 2024",
    delivery: "Available instantly on compatible devices",
    has_variations: false,
  },
  {
    asin: "B0D74SZ9NS",
    product_title: "Metal Gear Solid Selections Original Soundtrack",
    product_price: "$54.98",
    product_original_price: null,
    currency: "USD",
    product_star_rating: null,
    product_num_ratings: 0,
    product_url: "https://www.amazon.com/dp/B0D74SZ9NS",
    product_photo:
      "https://m.media-amazon.com/images/I/81TEJmhug0L._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$54.98",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: null,
    delivery:
      "FREE delivery Tue, Oct 22 Or fastest delivery Fri, Oct 18 This title will be released on October 18, 2024.",
    has_variations: false,
  },
  {
    asin: "B0D7MC3XH1",
    product_title: "YOYO School: YOYO Doll School life Dress up",
    product_price: "$0.00",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "5",
    product_num_ratings: 3,
    product_url: "https://www.amazon.com/dp/B0D7MC3XH1",
    product_photo:
      "https://m.media-amazon.com/images/I/81m++AruMtL._AC_UL960_FMwebp_QL65_.png",
    product_num_offers: 1,
    product_minimum_offer_price: "$0.00",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "Jun 20, 2024",
    delivery: "Available instantly on compatible devices",
    has_variations: false,
  },
  {
    asin: "B0CZ7NKH1T",
    product_title: "Triviascapes: relaxing trivia &amp; IQ quiz",
    product_price: "$0.00",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.2",
    product_num_ratings: 23,
    product_url: "https://www.amazon.com/dp/B0CZ7NKH1T",
    product_photo:
      "https://m.media-amazon.com/images/I/71DhfojGRZL._AC_UL960_FMwebp_QL65_.png",
    product_num_offers: 1,
    product_minimum_offer_price: "$0.00",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "Apr 10, 2024",
    delivery: "Available instantly on compatible devices",
    has_variations: false,
  },
  {
    asin: "B0CGVSQHNG",
    product_title: "Deeper Than the Dead (Vera Boyett Book 1)",
    product_price: "$4.99",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.3",
    product_num_ratings: 171,
    product_url: "https://www.amazon.com/dp/B0CGVSQHNG",
    product_photo:
      "https://m.media-amazon.com/images/I/817KwFYx4gL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$4.99",
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "Other formats: ",
    delivery: "This title will be released on August 1, 2024.",
    has_variations: false,
  },
  {
    asin: "B0D81GQ96G",
    product_title: "Smarter IP-TV : Player Pro",
    product_price: "$12.99",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "3.8",
    product_num_ratings: 4,
    product_url: "https://www.amazon.com/dp/B0D81GQ96G",
    product_photo:
      "https://m.media-amazon.com/images/I/61jFyIhWbTL._AC_UL960_FMwebp_QL65_.png",
    product_num_offers: 1,
    product_minimum_offer_price: "$12.99",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "Jun 26, 2024",
    delivery: "Available instantly on compatible devices",
    has_variations: false,
  },
  {
    asin: "B0D8K3Z4FT",
    product_title:
      "Ys Memoire The Oath of Felghana Nintendo Switch - D1 Refined Edition",
    product_price: "$59.99",
    product_original_price: null,
    currency: "USD",
    product_star_rating: null,
    product_num_ratings: 0,
    product_url: "https://www.amazon.com/dp/B0D8K3Z4FT",
    product_photo:
      "https://m.media-amazon.com/images/I/71LhvZ3JUpL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$59.99",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "Mar 31, 2025",
    delivery: "FREE deliveryThis item will be released on March 31, 2025.",
    has_variations: false,
  },
  {
    asin: "1538742578",
    product_title: "The Housemaid",
    product_price: "$6.96",
    product_original_price: "$12.99",
    currency: "USD",
    product_star_rating: "4.5",
    product_num_ratings: 319190,
    product_url: "https://www.amazon.com/dp/1538742578",
    product_photo:
      "https://m.media-amazon.com/images/I/81AHTyq2wVL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 119,
    product_minimum_offer_price: "$3.06",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "List: ",
    delivery: "FREE delivery Wed, Jul 10 on $35 of items shipped by Amazon",
    has_variations: false,
  },
  {
    asin: "B0D73NMM7N",
    product_title: "Fluvsies Merge Party",
    product_price: "$0.00",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "5",
    product_num_ratings: 2,
    product_url: "https://www.amazon.com/dp/B0D73NMM7N",
    product_photo:
      "https://m.media-amazon.com/images/I/81k3RzdCdxL._AC_UL960_FMwebp_QL65_.png",
    product_num_offers: 1,
    product_minimum_offer_price: "$0.00",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "Jun 27, 2024",
    delivery: "Available instantly on compatible devices",
    has_variations: false,
  },
  {
    asin: "B0D7W5JY1Y",
    product_title:
      "Paramount Presents: Bringing Out the Dead [4K UHD + Blu-Ray + Digital Copy]",
    product_price: "$39.99",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.5",
    product_num_ratings: 1119,
    product_url: "https://www.amazon.com/dp/B0D7W5JY1Y",
    product_photo:
      "https://m.media-amazon.com/images/I/61pWQhd0-hL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$39.99",
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "1K+ bought in past month",
    delivery:
      "FREE delivery Mon, Sep 23 Or fastest delivery Tue, Sep 17 This title will be released on September 17, 2024.",
    has_variations: false,
  },
  {
    asin: "B0CKNM2RS7",
    product_title: "Eruption",
    product_price: "$0.00",
    product_original_price: "$21.83",
    currency: "USD",
    product_star_rating: "4.3",
    product_num_ratings: 9813,
    product_url: "https://www.amazon.com/dp/B0CKNM2RS7",
    product_photo:
      "https://m.media-amazon.com/images/I/91jZ4396SPL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$0.00",
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "Other formats: ",
    delivery: "Available instantly",
    has_variations: false,
  },
  {
    asin: "B0D8J9HYGD",
    product_title:
      "Kingdom Of The Planet Of The Apes - UHD/BD Combo + Digital + Steelbook [4K UHD]",
    product_price: "$65.99",
    product_original_price: null,
    currency: "USD",
    product_star_rating: null,
    product_num_ratings: 0,
    product_url: "https://www.amazon.com/dp/B0D8J9HYGD",
    product_photo:
      "https://m.media-amazon.com/images/I/81O+BMeRFsL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$65.99",
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "Other formats: ",
    delivery:
      "$10.21 delivery Tue, Aug 27 This title will be released on August 27, 2024.",
    has_variations: false,
  },
  {
    asin: "B0D1XD1ZV3",
    product_title:
      "Apple AirPods Pro (2nd Generation) Wireless Ear Buds with USB-C Charging, Up to 2X More Active Noise Cancelling Bluetooth Headphones, Transparency Mode, Adaptive Audio, Personalized Spatial Audio",
    product_price: "$249.00",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.6",
    product_num_ratings: 1009,
    product_url: "https://www.amazon.com/dp/B0D1XD1ZV3",
    product_photo:
      "https://m.media-amazon.com/images/I/61SUj2aKoEL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 5,
    product_minimum_offer_price: "$206.80",
    is_best_seller: false,
    is_amazon_choice: true,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "10K+ bought in past month",
    delivery: "FREE delivery Wed, Jul 10",
    has_variations: false,
  },
  {
    asin: "B0D7TY6C1H",
    product_title:
      "Late Night With the Devil - Limited Edition Steelbook [Blu-Ray]",
    product_price: "$35.68",
    product_original_price: "$49.99",
    currency: "USD",
    product_star_rating: null,
    product_num_ratings: 0,
    product_url: "https://www.amazon.com/dp/B0D7TY6C1H",
    product_photo: null,
    product_num_offers: 1,
    product_minimum_offer_price: "$35.68",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "500+ bought in past month",
    delivery:
      "FREE delivery Mon, Sep 16 Or fastest delivery Tue, Sep 10 This title will be released on September 10, 2024.",
    has_variations: false,
  },
  {
    asin: "B0CQYH6LQ9",
    product_title:
      "8 Pack Refill Cartridge Kit Compatible with ZEVO Plug-in Light M364 and Max, Replacement 100% Fit (8 Refill Cartridges)",
    product_price: "$15.29",
    unit_price: "$1.91",
    unit_count: 8,
    product_original_price: "$17.99",
    currency: "USD",
    product_star_rating: "4.6",
    product_num_ratings: 1420,
    product_url: "https://www.amazon.com/dp/B0CQYH6LQ9",
    product_photo:
      "https://m.media-amazon.com/images/I/71iEIPz+JSL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$15.29",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "40K+ bought in past month",
    delivery: "FREE delivery Wed, Jul 10 on $35 of items shipped by Amazon",
    has_variations: false,
  },
  {
    asin: "B0D7KR99VL",
    product_title: "Get unlimited Free Robux 2024",
    product_price: "$0.00",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "1",
    product_num_ratings: 2,
    product_url: "https://www.amazon.com/dp/B0D7KR99VL",
    product_photo:
      "https://m.media-amazon.com/images/I/71H3ahAWJHL._AC_UL960_FMwebp_QL65_.png",
    product_num_offers: 1,
    product_minimum_offer_price: "$0.00",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "Jun 20, 2024",
    delivery: "Available instantly on compatible devices",
    has_variations: false,
  },
  {
    asin: "B0CPWYVX6H",
    product_title: "Energizer 2450 Lithium Coin Battery, 2 Pack",
    product_price: "$5.44",
    unit_price: "$2.72",
    unit_count: 2,
    product_original_price: "$8.98",
    currency: "USD",
    product_star_rating: "4.8",
    product_num_ratings: 1570,
    product_url: "https://www.amazon.com/dp/B0CPWYVX6H",
    product_photo:
      "https://m.media-amazon.com/images/I/71LSsuHdVBL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 11,
    product_minimum_offer_price: "$5.42",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "1K+ bought in past month",
    delivery: "FREE delivery Jul 11 - 15",
    has_variations: false,
  },
  {
    asin: "B0CX9CM41G",
    product_title: "Block Mini Craft Village",
    product_price: "$0.00",
    product_original_price: null,
    currency: "USD",
    product_star_rating: null,
    product_num_ratings: 0,
    product_url: "https://www.amazon.com/dp/B0CX9CM41G",
    product_photo:
      "https://m.media-amazon.com/images/I/81H6mknKhaL._AC_UL960_FMwebp_QL65_.png",
    product_num_offers: 1,
    product_minimum_offer_price: "$0.00",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "May 31, 2024",
    delivery: "Available instantly on compatible devices",
    has_variations: false,
  },
  {
    asin: "B00OZP5VRS",
    product_title: "A Court of Thorns and Roses",
    product_price: "$8.21",
    product_original_price: "$15.20",
    currency: "USD",
    product_star_rating: "4.6",
    product_num_ratings: 215583,
    product_url: "https://www.amazon.com/dp/B00OZP5VRS",
    product_photo:
      "https://m.media-amazon.com/images/I/81A-T+X6ukL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$8.21",
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "Digital List Price: ",
    delivery: "Available instantly",
    has_variations: false,
  },
  {
    asin: "B0D4FBLRTC",
    product_title: "People Sandbox Playgrounds",
    product_price: "$0.00",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "1.8",
    product_num_ratings: 3,
    product_url: "https://www.amazon.com/dp/B0D4FBLRTC",
    product_photo:
      "https://m.media-amazon.com/images/I/51vhEIwynYL._AC_UL960_FMwebp_QL65_.png",
    product_num_offers: 1,
    product_minimum_offer_price: "$0.00",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "May 17, 2024",
    delivery: "Available instantly on compatible devices",
    has_variations: false,
  },
  {
    asin: "B0D8JTTX3D",
    product_title: "The Chronicles Of Riddick 4K UHD",
    product_price: "$49.95",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.7",
    product_num_ratings: 7745,
    product_url: "https://www.amazon.com/dp/B0D8JTTX3D",
    product_photo:
      "https://m.media-amazon.com/images/I/8115yTKlBCL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$49.95",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "500+ bought in past month",
    delivery:
      "FREE delivery Mon, Sep 23 Or fastest delivery Tue, Sep 17 This title will be released on September 17, 2024.",
    has_variations: false,
  },
  {
    asin: "B0C4QD5VPB",
    product_title: "The Women: A Novel",
    product_price: "$0.00",
    product_original_price: "$24.74",
    currency: "USD",
    product_star_rating: "4.7",
    product_num_ratings: 124461,
    product_url: "https://www.amazon.com/dp/B0C4QD5VPB",
    product_photo:
      "https://m.media-amazon.com/images/I/91mP3553EzL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$0.00",
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "Other formats: ",
    delivery: "Available instantly",
    has_variations: false,
  },
  {
    asin: "B0CCPPQ38D",
    product_title: "Funny Story",
    product_price: "$0.00",
    product_original_price: "$20.25",
    currency: "USD",
    product_star_rating: "4.5",
    product_num_ratings: 42953,
    product_url: "https://www.amazon.com/dp/B0CCPPQ38D",
    product_photo:
      "https://m.media-amazon.com/images/I/71MmozgfmVL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$0.00",
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "Other formats: ",
    delivery: "Available instantly",
    has_variations: false,
  },
  {
    asin: "B0D37QVQW4",
    product_title: "MLB: Baseball Super League",
    product_price: "$0.00",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.1",
    product_num_ratings: 51,
    product_url: "https://www.amazon.com/dp/B0D37QVQW4",
    product_photo:
      "https://m.media-amazon.com/images/I/81LYuFcyLlL._AC_UL960_FMwebp_QL65_.png",
    product_num_offers: 1,
    product_minimum_offer_price: "$0.00",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "May 24, 2024",
    delivery: "Available instantly on compatible devices",
    has_variations: false,
  },
  {
    asin: "B0D3VHPLW1",
    product_title: "Furiosa: A Mad Max Saga (4K Ultra HD + Digital)",
    product_price: "$29.96",
    product_original_price: "$49.98",
    currency: "USD",
    product_star_rating: "4.4",
    product_num_ratings: 130,
    product_url: "https://www.amazon.com/dp/B0D3VHPLW1",
    product_photo:
      "https://m.media-amazon.com/images/I/81cqVE2vwvL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$29.96",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "3K+ bought in past month",
    delivery:
      "FREE delivery Mon, Aug 19 on $35 of items shipped by AmazonOr fastest delivery Tue, Aug 13 This title will be released on August 13, 2024.",
    has_variations: false,
  },
  {
    asin: "0140280197",
    product_title: "The 48 Laws of Power",
    product_price: "$14.55",
    product_original_price: "$26.00",
    currency: "USD",
    product_star_rating: "4.7",
    product_num_ratings: 77785,
    product_url: "https://www.amazon.com/dp/0140280197",
    product_photo:
      "https://m.media-amazon.com/images/I/611X8GI7hpL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 170,
    product_minimum_offer_price: "$7.91",
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "List: ",
    delivery: "FREE delivery Wed, Jul 10 on $35 of items shipped by Amazon",
    has_variations: false,
  },
  {
    asin: "B0CQCDMY2V",
    product_title: "The Beekeeper",
    product_price: "$3.99",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.6",
    product_num_ratings: 24293,
    product_url: "https://www.amazon.com/dp/B0CQCDMY2V",
    product_photo:
      "https://m.media-amazon.com/images/I/91yFa4jlW0L._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$3.99",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "2024",
    delivery: null,
    has_variations: false,
  },
  {
    asin: "B0CX379HYG",
    product_title:
      "Dickies Men&#x27;s Dri-tech Moisture Control No Show Socks (6/12 Pairs) (M-XXL)",
    product_price: "$15.99",
    unit_price: "$2.67",
    unit_count: 6,
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.6",
    product_num_ratings: 17423,
    product_url: "https://www.amazon.com/dp/B0CX379HYG",
    product_photo:
      "https://m.media-amazon.com/images/I/91VLjxlAbtL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$15.99",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "600+ bought in past month",
    delivery: "FREE delivery Wed, Jul 10 on $35 of items shipped by Amazon",
    has_variations: false,
  },
  {
    asin: "B0CW188Z2N",
    product_title: "Football League 2024",
    product_price: "$0.00",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.1",
    product_num_ratings: 47,
    product_url: "https://www.amazon.com/dp/B0CW188Z2N",
    product_photo:
      "https://m.media-amazon.com/images/I/81qVL2BFWhL._AC_UL960_FMwebp_QL65_.png",
    product_num_offers: 1,
    product_minimum_offer_price: "$0.00",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "Feb 26, 2024",
    delivery: "Available instantly on compatible devices",
    has_variations: false,
  },
  {
    asin: "0349132615",
    product_title: "The Housemaid&#x27;s Secret",
    product_price: "$7.68",
    product_original_price: "$12.99",
    currency: "USD",
    product_star_rating: "4.4",
    product_num_ratings: 168531,
    product_url: "https://www.amazon.com/dp/0349132615",
    product_photo:
      "https://m.media-amazon.com/images/I/81LZXcfKqJL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 58,
    product_minimum_offer_price: "$5.67",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "List: ",
    delivery: "FREE delivery Wed, Jul 10 on $35 of items shipped by Amazon",
    has_variations: false,
  },
  
  {
    asin: "B0DBFN3XT2",
    product_title: "Gacha&#x27;s Life For Dress Up",
    product_price: "$0.00",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "1",
    product_num_ratings: 3,
    product_url: "https://www.amazon.com/dp/B0DBFN3XT2",
    product_photo:
      "https://m.media-amazon.com/images/I/81axH9xCDPL._AC_UL960_FMwebp_QL65_.png",
    product_num_offers: 1,
    product_minimum_offer_price: "$0.00",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "Jul 28, 2024",
    delivery: "Available instantly on compatible devices",
    has_variations: false,
  },
  {
    asin: "B0DB7CTW13",
    product_title: "Youth Adventure Moment",
    product_price: "$0.00",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "2",
    product_num_ratings: 1,
    product_url: "https://www.amazon.com/dp/B0DB7CTW13",
    product_photo:
      "https://m.media-amazon.com/images/I/91PobXecidL._AC_UL960_FMwebp_QL65_.png",
    product_num_offers: 1,
    product_minimum_offer_price: "$0.00",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "Jul 26, 2024",
    delivery: "Available instantly on compatible devices",
    has_variations: false,
  },
  {
    asin: "B0DBFS9WWL",
    product_title: "Avatar Worlds Girls Dress Up",
    product_price: "$0.00",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "1",
    product_num_ratings: 3,
    product_url: "https://www.amazon.com/dp/B0DBFS9WWL",
    product_photo:
      "https://m.media-amazon.com/images/I/51KA8IMD9-L._AC_UL960_FMwebp_QL65_.png",
    product_num_offers: 1,
    product_minimum_offer_price: "$0.00",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "Jul 28, 2024",
    delivery: "Available instantly on compatible devices",
    has_variations: false,
  },
  {
    asin: "B0DBGMSG77",
    product_title: "Dash Sub Zero",
    product_price: "$0.00",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "1",
    product_num_ratings: 5,
    product_url: "https://www.amazon.com/dp/B0DBGMSG77",
    product_photo:
      "https://m.media-amazon.com/images/I/71xfSo9D0EL._AC_UL960_FMwebp_QL65_.png",
    product_num_offers: 1,
    product_minimum_offer_price: "$0.00",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "Jul 29, 2024",
    delivery: "Available instantly on compatible devices",
    has_variations: false,
  },
  {
    asin: "B0D2PKQGQV",
    product_title:
      "Hanes Men&#x27;s Pocket Undershirt Pack, Cotton Crew Neck T-Shirt, Moisture Wicking Tee, Assorted 6-Pack",
    product_price: "$22.00",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.4",
    product_num_ratings: 20909,
    product_url: "https://www.amazon.com/dp/B0D2PKQGQV",
    product_photo:
      "https://m.media-amazon.com/images/I/81v4ewQrCgL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$22.00",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "2K+ bought in past month",
    delivery:
      "FREE delivery Wed, Aug 21 on $35 of items shipped by AmazonOr fastest delivery Tue, Aug 20",
    has_variations: true,
  },
  {
    asin: "B0CW19SCVW",
    product_title: "IF",
    product_price: "$5.99",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.6",
    product_num_ratings: 2702,
    product_url: "https://www.amazon.com/dp/B0CW19SCVW",
    product_photo:
      "https://m.media-amazon.com/images/I/91HakgUE+9L._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$5.99",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "2024",
    delivery: null,
    has_variations: false,
  },
  {
    asin: "B0CQDFPMQW",
    product_title:
      "LMNT Zero Sugar Electrolytes - Variety Pack Bundle | Drink Mix | 36 Count",
    product_price: "$59.99",
    unit_price: "$7.90",
    unit_count: 8,
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.5",
    product_num_ratings: 18368,
    product_url: "https://www.amazon.com/dp/B0CQDFPMQW",
    product_photo:
      "https://m.media-amazon.com/images/I/81qGH-6amTL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$59.99",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "20K+ bought in past month",
    delivery: "FREE delivery Wed, Aug 21 Or fastest delivery Tue, Aug 20",
    has_variations: false,
  },
  {
    asin: "B0DB38JFZY",
    product_title: "Fortnite&#x27;s Game",
    product_price: "$0.00",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "2.5",
    product_num_ratings: 2,
    product_url: "https://www.amazon.com/dp/B0DB38JFZY",
    product_photo:
      "https://m.media-amazon.com/images/I/81D-vSmJ-lL._AC_UL960_FMwebp_QL65_.png",
    product_num_offers: 1,
    product_minimum_offer_price: "$0.00",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "Jul 24, 2024",
    delivery: "Available instantly on compatible devices",
    has_variations: false,
  },
  {
    asin: "B0DC5G7GQR",
    product_title: "Avatars Worlds",
    product_price: "$0.00",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "1",
    product_num_ratings: 1,
    product_url: "https://www.amazon.com/dp/B0DC5G7GQR",
    product_photo:
      "https://m.media-amazon.com/images/I/81hGA2SEEPL._AC_UL960_FMwebp_QL65_.png",
    product_num_offers: 1,
    product_minimum_offer_price: "$0.00",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "Aug 4, 2024",
    delivery: "Available instantly on compatible devices",
    has_variations: false,
  },
  {
    asin: "B0CL72PR7B",
    product_title: "A Death in Cornwall: A Novel (Gabriel Allon Book 24)",
    product_price: "$15.99",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.6",
    product_num_ratings: 10898,
    product_url: "https://www.amazon.com/dp/B0CL72PR7B",
    product_photo:
      "https://m.media-amazon.com/images/I/81KoDl1nhVL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$15.99",
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "Other formats: ",
    delivery: "Available instantly",
    has_variations: false,
  },
  {
    asin: "B0DBY4GM1P",
    product_title: "Kofi Blue Note Tone Poet Series",
    product_price: "$38.98",
    product_original_price: null,
    currency: "USD",
    product_star_rating: null,
    product_num_ratings: 0,
    product_url: "https://www.amazon.com/dp/B0DBY4GM1P",
    product_photo:
      "https://m.media-amazon.com/images/I/715hw2Nsx5L._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$38.98",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: null,
    delivery:
      "FREE delivery Tue, Oct 8 Or fastest delivery Fri, Oct 4 This title will be released on October 4, 2024.",
    has_variations: false,
  },
  {
    asin: "B0D6P3YR2B",
    product_title:
      "Carhartt Unisex Adult Key Keeper, Key Ring Holder with Self-Locking Metal Gate Clip",
    product_price: "$9.99",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "5",
    product_num_ratings: 3,
    product_url: "https://www.amazon.com/dp/B0D6P3YR2B",
    product_photo:
      "https://m.media-amazon.com/images/I/71PamT4JYDL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$9.99",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "400+ bought in past month",
    delivery:
      "FREE delivery Wed, Aug 21 on $35 of items shipped by AmazonOr fastest delivery Tue, Aug 20",
    has_variations: false,
  },
  {
    asin: "B0D49DL8XY",
    product_title: "A Quiet Place: Day One - Bonus X-Ray Edition",
    product_price: "$19.99",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.6",
    product_num_ratings: 61601,
    product_url: "https://www.amazon.com/dp/B0D49DL8XY",
    product_photo:
      "https://m.media-amazon.com/images/I/71BLocJT-8L._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$19.99",
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "2024",
    delivery: null,
    has_variations: false,
  },
  {
    asin: "B0DCK7F7DJ",
    product_title:
      "Inside Out 2 - UHD/BD Combo + Digital + Steelbook [Blu-ray]",
    product_price: "$67.99",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4",
    product_num_ratings: 1,
    product_url: "https://www.amazon.com/dp/B0DCK7F7DJ",
    product_photo:
      "https://m.media-amazon.com/images/I/71PjnOf620L._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$67.99",
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "2K+ bought in past month",
    delivery: "FREE deliveryThis title will be released on September 10, 2024.",
    has_variations: false,
  },
  {
    asin: "B01DYO4MVG",
    product_title: "A Court of Mist and Fury",
    product_price: "$0.00",
    product_original_price: "$25.79",
    currency: "USD",
    product_star_rating: "4.8",
    product_num_ratings: 203355,
    product_url: "https://www.amazon.com/dp/B01DYO4MVG",
    product_photo:
      "https://m.media-amazon.com/images/I/81rXZ3NDrKL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$0.00",
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "Other formats: ",
    delivery: "Available instantly",
    has_variations: false,
  },
  {
    asin: "B0D1WXVQTN",
    product_title:
      "Apple AirPods (3rd Generation) Wireless Ear Buds, Bluetooth Headphones, Personalized Spatial Audio, Sweat and Water Resistant, Lightning Charging Case Included, Up to 30 Hours of Battery Life",
    product_price: "$139.99",
    product_original_price: "$169.00",
    currency: "USD",
    product_star_rating: "4.3",
    product_num_ratings: 1668,
    product_url: "https://www.amazon.com/dp/B0D1WXVQTN",
    product_photo:
      "https://m.media-amazon.com/images/I/61df2M5+OnL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 4,
    product_minimum_offer_price: "$107.83",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "10K+ bought in past month",
    delivery: "FREE delivery Wed, Aug 21 Or fastest delivery Tue, Aug 20",
    has_variations: false,
  },
  {
    asin: "B0D9Y8DSMM",
    product_title: "Mad shark",
    product_price: "$0.00",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "3.6",
    product_num_ratings: 4,
    product_url: "https://www.amazon.com/dp/B0D9Y8DSMM",
    product_photo:
      "https://m.media-amazon.com/images/I/81vUzgBFuhL._AC_UL960_FMwebp_QL65_.png",
    product_num_offers: 1,
    product_minimum_offer_price: "$0.00",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "Jul 23, 2024",
    delivery: "Available instantly on compatible devices",
    has_variations: false,
  },
  {
    asin: "B0CPWYVX6H",
    product_title: "Energizer 2450 Lithium Coin Battery, 2 Pack",
    product_price: "$4.05",
    unit_price: "$2.03",
    unit_count: 2,
    product_original_price: "$8.98",
    currency: "USD",
    product_star_rating: "4.8",
    product_num_ratings: 1607,
    product_url: "https://www.amazon.com/dp/B0CPWYVX6H",
    product_photo:
      "https://m.media-amazon.com/images/I/71LSsuHdVBL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$4.05",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "6K+ bought in past month",
    delivery: "FREE delivery Tue, Aug 27 Or fastest delivery Aug 22 - 26",
    has_variations: false,
  },
  {
    asin: "B09XRF2SWN",
    product_title: "The Housemaid",
    product_price: "$0.00",
    product_original_price: "$19.95",
    currency: "USD",
    product_star_rating: "4.5",
    product_num_ratings: 347069,
    product_url: "https://www.amazon.com/dp/B09XRF2SWN",
    product_photo:
      "https://m.media-amazon.com/images/I/81Y1TlywXDL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$0.00",
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "Other formats: ",
    delivery: "Available instantly",
    has_variations: false,
  },
  {
    asin: "B0CX5R9P63",
    product_title: "Challengers",
    product_price: "$3.99",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "3.9",
    product_num_ratings: 948,
    product_url: "https://www.amazon.com/dp/B0CX5R9P63",
    product_photo:
      "https://m.media-amazon.com/images/I/A1qhefT6QFL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$3.99",
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "2024",
    delivery: null,
    has_variations: false,
  },
  {
    asin: "B0DD1QSTNR",
    product_title: "Among&#x27;s US",
    product_price: "$0.00",
    product_original_price: null,
    currency: "USD",
    product_star_rating: null,
    product_num_ratings: 0,
    product_url: "https://www.amazon.com/dp/B0DD1QSTNR",
    product_photo:
      "https://m.media-amazon.com/images/I/71VYS24gEML._AC_UL960_FMwebp_QL65_.png",
    product_num_offers: 1,
    product_minimum_offer_price: "$0.00",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "Aug 13, 2024",
    delivery: "Available instantly on compatible devices",
    has_variations: false,
  },
  {
    asin: "B0DC4J6S79",
    product_title: "Real City Gangster Offline Urban City Game 3D",
    product_price: "$0.00",
    product_original_price: null,
    currency: "USD",
    product_star_rating: null,
    product_num_ratings: 0,
    product_url: "https://www.amazon.com/dp/B0DC4J6S79",
    product_photo:
      "https://m.media-amazon.com/images/I/91K0UsTEaqL._AC_UL960_FMwebp_QL65_.png",
    product_num_offers: 1,
    product_minimum_offer_price: "$0.00",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "Aug 4, 2024",
    delivery: "Available instantly on compatible devices",
    has_variations: false,
  },
  {
    asin: "B0DBL4QQXS",
    product_title: "Quality Wallpaper",
    product_price: "$0.00",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "1.6",
    product_num_ratings: 6,
    product_url: "https://www.amazon.com/dp/B0DBL4QQXS",
    product_photo:
      "https://m.media-amazon.com/images/I/41NQuqQS+PL._AC_UL960_FMwebp_QL65_.png",
    product_num_offers: 1,
    product_minimum_offer_price: "$0.00",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "Jul 30, 2024",
    delivery: "Available instantly on compatible devices",
    has_variations: false,
  },
  {
    asin: "B0D9YZ56G9",
    product_title: "Gachas Clubs Worlds",
    product_price: "$0.00",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "1",
    product_num_ratings: 1,
    product_url: "https://www.amazon.com/dp/B0D9YZ56G9",
    product_photo:
      "https://m.media-amazon.com/images/I/81LVb9l-zuL._AC_UL960_FMwebp_QL65_.png",
    product_num_offers: 1,
    product_minimum_offer_price: "$0.00",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "Jul 23, 2024",
    delivery: "Available instantly on compatible devices",
    has_variations: false,
  },
  {
    asin: "B0DD4ZN3WM",
    product_title: "Into the Light: The Solo Albums",
    product_price: "$69.98",
    product_original_price: null,
    currency: "USD",
    product_star_rating: null,
    product_num_ratings: 0,
    product_url: "https://www.amazon.com/dp/B0DD4ZN3WM",
    product_photo:
      "https://m.media-amazon.com/images/I/8182imwe26L._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$69.98",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "Other format: ",
    delivery:
      "FREE delivery Tue, Oct 29 Or fastest delivery Fri, Oct 25 This title will be released on October 25, 2024.",
    has_variations: false,
  },
  {
    asin: "B0D6JZYX31",
    product_title: "Despicable Me 4 (Includes 2 Mini-Movies)",
    product_price: "$19.99",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.7",
    product_num_ratings: 214,
    product_url: "https://www.amazon.com/dp/B0D6JZYX31",
    product_photo:
      "https://m.media-amazon.com/images/I/81YnCOk7+oL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$19.99",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "2024",
    delivery: null,
    has_variations: false,
  },
  {
    asin: "B0CZ7Q9YFN",
    product_title:
      "The Children&#x27;s Place Baby Girls&#x27; and Toddler Short Sleeve Everyday Dresses",
    product_price: "$6.88",
    product_original_price: "$9.18",
    currency: "USD",
    product_star_rating: "4.8",
    product_num_ratings: 592,
    product_url: "https://www.amazon.com/dp/B0CZ7Q9YFN",
    product_photo:
      "https://m.media-amazon.com/images/I/81wG3I+y4TL._MCnd_AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$6.88",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "200+ bought in past month",
    delivery: "FREE delivery on $35 shipped by Amazon.",
    has_variations: true,
  },
  {
    asin: "B0C4JMJBNX",
    product_title: "Iron Flame (The Empyrean Book 2)",
    product_price: "$14.99",
    product_original_price: "$29.99",
    currency: "USD",
    product_star_rating: "4.6",
    product_num_ratings: 182604,
    product_url: "https://www.amazon.com/dp/B0C4JMJBNX",
    product_photo:
      "https://m.media-amazon.com/images/I/912fTvsUKLL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$14.99",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "Print List Price: ",
    delivery: "Available instantly",
    has_variations: false,
  },
  {
    asin: "B0DCDPFVY7",
    product_title:
      "Halloween and Ash vs Evil Dead RetroRealms Double Feature Special Edition - Xbox Series X",
    product_price: "$79.99",
    product_original_price: null,
    currency: "USD",
    product_star_rating: null,
    product_num_ratings: 0,
    product_url: "https://www.amazon.com/dp/B0DCDPFVY7",
    product_photo:
      "https://m.media-amazon.com/images/I/514MlAOCuuL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$79.99",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: true,
    sales_volume: "Oct 18, 2024",
    delivery: "FREE deliveryThis item will be released on October 18, 2024.",
    has_variations: false,
  },
  {
    asin: "B08FCXG1SB",
    product_title: "A Court of Silver Flames",
    product_price: "$0.00",
    product_original_price: "$30.09",
    currency: "USD",
    product_star_rating: "4.8",
    product_num_ratings: 166333,
    product_url: "https://www.amazon.com/dp/B08FCXG1SB",
    product_photo:
      "https://m.media-amazon.com/images/I/91dvInY9WWL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$0.00",
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "Other formats: ",
    delivery: "Available instantly",
    has_variations: false,
  },
  {
    asin: "B0DB9JQKHN",
    product_title: "Brawl&#x27;s Staar&#x27;s",
    product_price: "$0.00",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "5",
    product_num_ratings: 1,
    product_url: "https://www.amazon.com/dp/B0DB9JQKHN",
    product_photo:
      "https://m.media-amazon.com/images/I/51edMhmMC2L._AC_UL960_FMwebp_QL65_.png",
    product_num_offers: 1,
    product_minimum_offer_price: "$0.00",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "Jul 27, 2024",
    delivery: "Available instantly on compatible devices",
    has_variations: false,
  },
  {
    asin: "B0D6XM5LS3",
    product_title: "Twisters",
    product_price: "$19.99",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.1",
    product_num_ratings: 39,
    product_url: "https://www.amazon.com/dp/B0D6XM5LS3",
    product_photo:
      "https://m.media-amazon.com/images/I/81Pa0UsZMpL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$19.99",
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "2024",
    delivery: null,
    has_variations: false,
  },
  {
    asin: "B0DCKFZ1V6",
    product_title: "FINAL FANTASY I-VI Collection Anniversary Edition (PS4)",
    product_price: "$74.99",
    product_original_price: null,
    currency: "USD",
    product_star_rating: null,
    product_num_ratings: 0,
    product_url: "https://www.amazon.com/dp/B0DCKFZ1V6",
    product_photo:
      "https://m.media-amazon.com/images/I/71MNXiXewnL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$74.99",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "Oct 8, 2024",
    delivery: "FREE deliveryThis item will be released on October 8, 2024.",
    has_variations: false,
  },
  {
    asin: "B0D8QTNVZZ",
    product_title:
      "Goblin Slayer -Another Adventurer- Nightmare Feast - Nintendo Switch",
    product_price: "$49.99",
    product_original_price: null,
    currency: "USD",
    product_star_rating: null,
    product_num_ratings: 0,
    product_url: "https://www.amazon.com/dp/B0D8QTNVZZ",
    product_photo:
      "https://m.media-amazon.com/images/I/81Kbp42AhiL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$49.99",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "Oct 25, 2024",
    delivery: "FREE deliveryThis item will be released on October 25, 2024.",
    has_variations: false,
  },
  {
    asin: "B0CCPPQ38D",
    product_title: "Funny Story",
    product_price: "$0.00",
    product_original_price: "$20.25",
    currency: "USD",
    product_star_rating: "4.5",
    product_num_ratings: 56188,
    product_url: "https://www.amazon.com/dp/B0CCPPQ38D",
    product_photo:
      "https://m.media-amazon.com/images/I/71MmozgfmVL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$0.00",
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "Other formats: ",
    delivery: "Available instantly",
    has_variations: false,
  },
  {
    asin: "B0DCJ8M3MT",
    product_title: "abouTZU Heaven ver.",
    product_price: "$32.98",
    product_original_price: null,
    currency: "USD",
    product_star_rating: null,
    product_num_ratings: 0,
    product_url: "https://www.amazon.com/dp/B0DCJ8M3MT",
    product_photo:
      "https://m.media-amazon.com/images/I/61tkG+5LnvL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$32.98",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: null,
    delivery:
      "FREE delivery on $35 shipped by Amazon.This title will be released on September 6, 2024.",
    has_variations: false,
  },
  {
    asin: "B0DCKFWW1V",
    product_title: "FINAL FANTASY I-VI Collection Anniversary Edition (NSW)",
    product_price: "$74.99",
    product_original_price: null,
    currency: "USD",
    product_star_rating: null,
    product_num_ratings: 0,
    product_url: "https://www.amazon.com/dp/B0DCKFWW1V",
    product_photo:
      "https://m.media-amazon.com/images/I/71QWO4tJLoL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$74.99",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "Oct 8, 2024",
    delivery: "FREE deliveryThis item will be released on October 8, 2024.",
    has_variations: false,
  },
  {
    asin: "B0DBJC933Y",
    product_title: "Vita Spider for Seniors",
    product_price: "$0.00",
    product_original_price: null,
    currency: "USD",
    product_star_rating: null,
    product_num_ratings: 0,
    product_url: "https://www.amazon.com/dp/B0DBJC933Y",
    product_photo:
      "https://m.media-amazon.com/images/I/81z5ErNPtUL._AC_UL960_FMwebp_QL65_.png",
    product_num_offers: 1,
    product_minimum_offer_price: "$0.00",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "Aug 1, 2024",
    delivery: "Available instantly on compatible devices",
    has_variations: false,
  },
  {
    asin: "B0CDWHN8FK",
    product_title: "Just for the Summer",
    product_price: "$11.99",
    product_original_price: "$17.99",
    currency: "USD",
    product_star_rating: "4.6",
    product_num_ratings: 41624,
    product_url: "https://www.amazon.com/dp/B0CDWHN8FK",
    product_photo:
      "https://m.media-amazon.com/images/I/81tVBUv75vL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$11.99",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "Print List Price: ",
    delivery: "Available instantly",
    has_variations: false,
  },
  {
    asin: "B075818VDG",
    product_title:
      "A Court of Frost and Starlight (A Court of Thorns and Roses Book 4)",
    product_price: "$8.30",
    product_original_price: "$13.60",
    currency: "USD",
    product_star_rating: "4.3",
    product_num_ratings: 125997,
    product_url: "https://www.amazon.com/dp/B075818VDG",
    product_photo:
      "https://m.media-amazon.com/images/I/81lbIOH6GiL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$8.30",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "Digital List Price: ",
    delivery: "Available instantly",
    has_variations: false,
  },
  {
    asin: "B0DD7CCDJ3",
    product_title: "Stickman Battle Playground 2",
    product_price: "$0.00",
    product_original_price: null,
    currency: "USD",
    product_star_rating: null,
    product_num_ratings: 0,
    product_url: "https://www.amazon.com/dp/B0DD7CCDJ3",
    product_photo:
      "https://m.media-amazon.com/images/I/71bqtFvcswL._AC_UL960_FMwebp_QL65_.png",
    product_num_offers: 1,
    product_minimum_offer_price: "$0.00",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "Aug 15, 2024",
    delivery: "Available instantly on compatible devices",
    has_variations: false,
  },
  {
    asin: "B0DCB6G6NY",
    product_title: "Godzilla Minus One (4K Ultra HD + Blu-ray)",
    product_price: "$35.57",
    product_original_price: "$49.98",
    currency: "USD",
    product_star_rating: "5",
    product_num_ratings: 2,
    product_url: "https://www.amazon.com/dp/B0DCB6G6NY",
    product_photo:
      "https://m.media-amazon.com/images/I/91rDyK8grkL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$35.57",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "2K+ bought in past month",
    delivery: "FREE deliveryThis title has not yet been released.",
    has_variations: false,
  },
  {
    asin: "B0D9W6HS8Y",
    product_title: "Ninja Scroll - Limited Edition Steelbook [Blu-Ray]",
    product_price: "$47.49",
    product_original_price: "$69.98",
    currency: "USD",
    product_star_rating: "4.8",
    product_num_ratings: 3459,
    product_url: "https://www.amazon.com/dp/B0D9W6HS8Y",
    product_photo:
      "https://m.media-amazon.com/images/I/718nQVKEpXL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$47.49",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "600+ bought in past month",
    delivery:
      "FREE delivery Mon, Oct 28 Or fastest delivery Tue, Oct 22 This title will be released on October 22, 2024.",
    has_variations: false,
  },
  {
    asin: "0140280197",
    product_title: "The 48 Laws of Power",
    product_price: "$14.55",
    product_original_price: "$26.00",
    currency: "USD",
    product_star_rating: "4.7",
    product_num_ratings: 78916,
    product_url: "https://www.amazon.com/dp/0140280197",
    product_photo:
      "https://m.media-amazon.com/images/I/611X8GI7hpL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 62,
    product_minimum_offer_price: "$5.84",
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "List: ",
    delivery:
      "FREE delivery Wed, Aug 21 on $35 of items shipped by AmazonOr fastest delivery Tue, Aug 20",
    has_variations: false,
  },
  {
    asin: "B0DCSZZMXR",
    product_title: "1994 - Yellow",
    product_price: "$27.98",
    product_original_price: null,
    currency: "USD",
    product_star_rating: null,
    product_num_ratings: 0,
    product_url: "https://www.amazon.com/dp/B0DCSZZMXR",
    product_photo:
      "https://m.media-amazon.com/images/I/81LBFvi+kYL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$27.98",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: null,
    delivery:
      "FREE delivery Tue, Oct 22 on $35 of items shipped by AmazonOr fastest delivery Fri, Oct 18 This title will be released on October 18, 2024.",
    has_variations: false,
  },
  {
    asin: "B0DBJ6JPNG",
    product_title: "Hymnal of a Troubled Man&#x27;s Mind",
    product_price: "$14.98",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "5",
    product_num_ratings: 9,
    product_url: "https://www.amazon.com/dp/B0DBJ6JPNG",
    product_photo:
      "https://m.media-amazon.com/images/I/91THAeu8zkL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$14.98",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "Other format: ",
    delivery:
      "FREE delivery Tue, Oct 1 on $35 of items shipped by AmazonOr fastest delivery Fri, Sep 27 This title will be released on September 27, 2024.",
    has_variations: false,
  },
  {
    asin: "B071RR4DPV",
    product_title: "A Court of Wings and Ruin",
    product_price: "$0.00",
    product_original_price: "$30.09",
    currency: "USD",
    product_star_rating: "4.8",
    product_num_ratings: 188049,
    product_url: "https://www.amazon.com/dp/B071RR4DPV",
    product_photo:
      "https://m.media-amazon.com/images/I/81kScfXoFbL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$0.00",
    is_best_seller: false,
    is_amazon_choice: false,
    is_prime: false,
    climate_pledge_friendly: false,
    sales_volume: "Other formats: ",
    delivery: "Available instantly",
    has_variations: false,
  },
  {
    asin: "B0CHGZSD2B",
    product_title:
      "adidas Alliance Sackpack Drawstring Backpack Gym Bag, Sandy Pink/White, One Size",
    product_price: "$20.00",
    product_original_price: null,
    currency: "USD",
    product_star_rating: "4.8",
    product_num_ratings: 27380,
    product_url: "https://www.amazon.com/dp/B0CHGZSD2B",
    product_photo:
      "https://m.media-amazon.com/images/I/81e7aKwcxLL._AC_UL960_FMwebp_QL65_.jpg",
    product_num_offers: 1,
    product_minimum_offer_price: "$20.00",
    is_best_seller: true,
    is_amazon_choice: false,
    is_prime: true,
    climate_pledge_friendly: false,
    sales_volume: "500+ bought in past month",
    delivery: "FREE delivery Wed, Aug 21 on $35 of items shipped by Amazon",
    has_variations: true,
  },
];

